name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./model/pom.xml
          mvn clean package -f ./notice/pom.xml
          mvn clean package -f ./core/pom.xml
          mvn clean package -f ./target/pom.xml

      - name: Docker Build and push for Model
        uses: docker/build-push-action@v4
        with:
          context: ./model
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/model:latest
            ghcr.io/${{ github.repository }}/model:${{ github.ref_name }}
            
      - name: Docker Build and push for Notice
        uses: docker/build-push-action@v4
        with:
          context: ./notice
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/notice:latest
            ghcr.io/${{ github.repository }}/notice:${{ github.ref_name }}
            
      - name: Docker Build and push for Core
        uses: docker/build-push-action@v4
        with:
          context: ./core
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/core:latest
            ghcr.io/${{ github.repository }}/core:${{ github.ref_name }}
            
      - name: Docker Build and push for Target
        uses: docker/build-push-action@v4
        with:
          context: ./target
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/target:latest
            ghcr.io/${{ github.repository }}/target:${{ github.ref_name }}
            
